### ISSUE TITLE
Question about rectifying predictions

### ISSUE THREAD

**Issue by cxy1996** [EdenBelouadah/class-incremental-learning#1]
Thank you for your work！I found that the definition of function 1 in your paper is different from that in the code. `val_rectified_np_scores[o] *= new_classes_means[o] / old_classes_means[o] * models_means[b] / models_means[int(o / P) + 1]` Is there anything wrong?

**Comment by EdenBelouadah** [comment]
The equation is the same in the paper. We take the score of the class, we multiply it by the average class mean score in the initial state when it was learned for the first time, divided by its average score in the current state. The second factor is the model confidence in the current state divide by the model confidence in the initial state when we learned the class for the first time. Model confidence is the average of the maximum prediction score that the model gives for training data coming from new classes.

**Comment by EdenBelouadah** [comment]
> The equation is the same in the paper. We take the score of the class, we multiply it by the average class mean score in the initial state when it was learned for the first time, divided by its average score in the current state. The second factor is the model confidence in the current state divide by the model confidence in the initial state when we learned the class for the first time. Model confidence is the average of the maximum prediction score that the model gives for training data coming from new classes.

We changed the variables names in the code to eliminate confusion and we added some comments to clarify the followed steps. The code logic is the same.
