### ISSUE TITLE
data list format

### ISSUE THREAD

**Issue by wuyuebupt** [EdenBelouadah/class-incremental-learning#2]
Hi, I tried to run the il2m code with the first batch of data on ILSVRC ImageNet. It requires extra data list files data/images_list_files/ilsvrc/S\~10/batch1/train.lst and data/images_list_files/ilsvrc/S\~10/batch1/val.lst, which I can not find in the repo. 

I do check the code and find that it might be in a format "image_path class_label" for each line. 

Can you provide us all 10 batch file lists as? Or teach us how to generate these lists so that we can generate these lists by ourselves? 

Thanks for the help!

**Comment by EdenBelouadah** [comment]
The data you are looking for is already provided in the drive repository :   [here](https://drive.google.com/drive/folders/1TiQnvY5LKAaT0y9IUprw-gQru6g8Ehqu), more specifically : [here](https://drive.google.com/drive/folders/1O2OBC2a39Bo7xDweDBVHZ6piFTbgXpU-)

**Comment by wuyuebupt** [comment]
@EdenBelouadah Thanks for the reply. I miss that information in the readme.
