### ISSUE TITLE
unbalanced image list files folder

### ISSUE THREAD

**Issue by tyler-hayes** [EdenBelouadah/class-incremental-learning#3]
Hello,

I am interested in running the ScaIL code for a different ordering of ImageNet. I was able to figure out how to create the necessary image list files at `data/images_list_files/ilsvrc/S~10/` for the `batch1`, `separated`, and `accumulated` directories. However, I am having some problems creating the files for the `unbalanced/train/K~###/X_old` directory. I understand that these files should contain roughly `###` images, but was wondering if you had a script to easily generate these files or something else to help with my new ordering?

Thanks!

**Comment by EdenBelouadah** [comment]
Hi,
I added the requested code [here](https://github.com/EdenBelouadah/class-incremental-learning/blob/master/scail/codes/prepare_imbalanced_list_files.py).
Note that lists for past class exemplars are randomly generated, the code is not deterministic and the results could change from an execution to another.

If you want to select exemplars based on herding mechanism, execute ft_herd.py, it generates automatically the requested lists.
