### ISSUE TITLE
How to get image for cifar100 in ail

### ISSUE THREAD

**Issue by Ffffffffchopin** [EdenBelouadah/class-incremental-learning#8]
Hello Eden,thanks a lot for your code which help me a lot.But as a green hand for coding,I can't solve the problem to get image for ail.

After get folder from google drive you provide,it come with this erroe

`Cant find /scratch_ssd2/cifar100/data/cifar100/cifar-100-python/fine/train/apple/mcintosh_s_000643.png`

In fact I don't know where to find the image listed on the .txt files.

**Comment by EdenBelouadah** [comment]
Hi,
Thank you for your interest in our work.
You should download the dataset cifar from its official website. Then, modify the file with the correct images paths in you computer
